# Generated by Django 5.2.5 on 2025-11-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_year',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
