# Generated by Django 5.2.5 on 2025-11-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0002_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
