# Generated by Django 5.2.5 on 2025-11-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0003_owner_age_owner_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='age',
        ),
    ]
