# Generated by Django 5.2.5 on 2025-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0004_remove_owner_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model_year',
            field=models.DateField(default=2000),
        ),
    ]
