# Generated by Django 5.2.5 on 2025-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insapp', '0005_alter_vehicle_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model_year',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
